server:
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hmdp?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  redis:
    host: 192.168.101.65
    port: 6379
    password: redis
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
#  redis:
#    sentinel:
#      nodes:
#        - 43.138.17.148:27001
#        - 43.138.17.148:27002
#        - 43.138.17.148:27003
#      master: mymaster
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug

rocketmq:
  name-server: 192.168.101.65:9876
  consumer:
    access-key: rocketmq2
    secret-key: 12345678
  producer:
    group: seckill-producer-group
    access-key: rocketmq2
    secret-key: 12345678